# Generated by Django 4.2.2 on 2023-07-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('feedback_email', models.CharField(max_length=100)),
                ('feedback_msg', models.CharField(max_length=500)),
            ],
        ),
    ]
