# Generated by Django 4.2.2 on 2023-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_category', models.CharField(max_length=50)),
                ('ac_followers', models.CharField(max_length=50)),
                ('ac_age', models.CharField(max_length=50)),
                ('ac_dob', models.DateField(max_length=50)),
                ('ac_name', models.CharField(max_length=50)),
                ('ac_email', models.CharField(max_length=50)),
            ],
        ),
    ]
