# Generated by Django 4.2.2 on 2023-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0002_sellacc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellacc',
            name='ac_dob',
        ),
        migrations.AddField(
            model_name='sellacc',
            name='ac_fullname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
