# Generated by Django 4.2.2 on 2023-07-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=100)),
                ('ac_join_date', models.CharField(max_length=50)),
                ('ac_rating', models.CharField(max_length=50)),
                ('ac_bio', models.CharField(max_length=100)),
                ('ac_followers', models.CharField(max_length=50)),
                ('ac_price', models.CharField(max_length=50)),
                ('ac_info', models.CharField(max_length=500)),
                ('ac_pic_one', models.ImageField(default='/static/images/travel.jpg', upload_to='static/images/sellAccount/')),
                ('ac_pic_two', models.ImageField(default='/static/images/travel.jpg', upload_to='static/images/sellAccount/')),
                ('ac_pic_three', models.ImageField(default='/static/images/travel.jpg', upload_to='static/images/sellAccount/')),
                ('ac_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digi.category')),
            ],
        ),
    ]
