# Generated by Django 4.2.2 on 2023-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0005_instaaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='ac_dp',
            field=models.ImageField(default='/static/images/travel.jpg', upload_to='static/images/sellAccount/'),
        ),
        migrations.AlterField(
            model_name='instaaccounts',
            name='ac_join_date',
            field=models.DateField(),
        ),
    ]
