# Generated by Django 4.2.2 on 2023-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0006_instaaccounts_ac_dp_alter_instaaccounts_ac_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociallinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(max_length=100)),
            ],
        ),
    ]
