# Generated by Django 4.2.2 on 2023-07-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digi', '0007_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('sell_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi.instaaccounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
