# Generated by Django 4.2.2 on 2023-07-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sell_ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digi.instaaccounts'),
        ),
        migrations.AlterField(
            model_name='instaaccounts',
            name='ac_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi.category'),
        ),
    ]
