# Generated by Django 4.2.2 on 2023-07-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0009_alter_cart_sell_ac_alter_instaaccounts_ac_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=10)),
                ('followers_img', models.ImageField(default='/static/images/travel.jpg', upload_to='static/images/')),
            ],
        ),
    ]
