# Generated by Django 4.2.2 on 2023-07-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0010_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='ac_follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digi.followers'),
        ),
    ]
